CS492-FE-Dev-Team-Project/FE-Dev-Client

- client/src/lib/socket/socketProvider.tsx
- client/src/lib/socket/types.ts
- client/src/pages/socketTestPage.tsx
- server/package.json
- server/src/config/index.ts
- server/src/ioHandler/index.ts
- server/src/loader/express.ts
- server/src/loader/logger.ts
- server/src/loader/orm.ts
- server/src/routes/classRoute/classData.ts
- server/src/routes/classRoute/index.ts
- server/src/routes/index.ts
- server/src/server.ts
- server/yarn.lock
dd75e552eb5a0dcb8e19e1a42364e12dc6b13ff1: `winston` 이용해서 logger 만들기 
30c87aef09a3a7e83c8c96cc3f8df924d94906bf: `express` middleware 등록
e5c3287ac9690b0f9443434b4ed1ac9f0f62a2b5: `express` 이용한 http api 예제
4acf3ed35df7cb9b6abce59041e94f19d4937fe5: `socket.io` 이용한 client와의 웹소켓 통신
형들이 가장 많이 구현하게 될 부분이 웹소켓을 이용하게될 부분이라고 생각해 이 부분 예제를 만들어보았습니다.
서버에 데이터를 보내고 그대로 돌려보내는 예시입니다.
실행하는 방법은 `App.tsx`에서 아래와 같이 만들어서 실행 가능합니다!
```js
import SocketTextPage from './pages/socketTestPage';
...
const App = (): React.ReactElement<any, any> => {
return (
<div className="App">
{SocketTextPage}
</div>
);
};
```
- Clientside:
1. `SocketProvider` 이용해서 `Socket.io-client` context를 child Component에게 제공
이렇게 감싸주면 하위 컴포넌트들에서 `useSocket`이나 `useSocketEvent` hook을 사용할 수 있게 됩니다.
```js
// client/src/pages/socketTestPage.tsx:48 …
```
> Impl server template code#4

- .husky/pre-commit
- package.json
- server/Dockerfile
- server/package.json
- server/src/entity/class.ts
- server/src/entity/classMember.ts
- server/src/entity/lecture.ts
- server/src/entity/marker.ts
- server/src/ioHandler/index.ts
- #8 
- DB Table 설계함
- 구현사항이 확정되지 않았고 우선순위가 낮은 quiz, notice, 개인채팅을 제외하고 DB 설계
- User (`server/src/entity/user.ts`)
유저 계정 entity입니다.
```js
@Entity()
export default class User extends BaseEntity {
@PrimaryGeneratedColumn()
public id: number;
@CreateDateColumn()
public createdDate: Date;
@UpdateDateColumn()
public updatedDate: Date;
@Column('varchar')
public userName: string;
// TODO: add SSOAcounts
@OneToMany(() => ClassMember, classMember => classMember.member)
public classes: ClassMember[];
}
```
- ClassMember (`server/src/entity/classMember.ts`)
User과 Class를 이어주는 Jointable입니다. 
```js
@Entity()
export default class ClassMember extends BaseEntity {
@PrimaryGeneratedColumn()
public id: number;
@CreateDateColumn()
public createdDate: Date;
@UpdateDateColumn()
public updatedDate: Date; …
```
> Create db schema#8

- client/.eslintrc.js
- client/package.json
- client/src/App.tsx
- client/src/components/timeline.tsx
- client/src/components/youtube.tsx
- client/src/style/youtube.css
유저가 특정 시간대에 마킹을 생성하는 기능인 'timeline component'를 구현했습니다.
1. Time component (`client/src/components/timeline.tsx`)
2. Progress bar (only for participants - `client/src/components/youtube.tsx` 안에)
마우스 호버 시, timeline component + progress bar 나타남
클릭 시 (나중에 채팅창과 연계할 것)
<br>
YouTube player 위에 overlay될 Time component를 구현했습니다.
요렇게 데이터가 주어지면
```JS
// client/src/components/youtube.tsx
const [flagInfoArr, setFlagInfoArr] = useState<Array<flagInfo>>([
{ time: 30, message: 'A' },
{ time: 50, message: 'B' },
]); // 🐛 Mockup data; get real 'flagInfoArr' data by calling DB API
```
`Array.map`을 이용해서 `Flag` 컴포넌트를 생성합니다. 
```JS
import Flag from './timeline';
...
return(
{flagInfoArr.map((info, idx) => {
...
return (
<Flag
time={(info.time / videoDuration.current) * 100}
message={info.message}
/>
);
})}
);
``` …
> Timeline component#13

- client/src/App.tsx
- client/src/components/floatConnectionStatus.tsx
- client/src/components/leftmenu/leftmenu.tsx
- client/src/components/leftmenu/leftmenutab.tsx
- client/src/components/youtube.tsx
- client/src/pages/classPage.tsx
- client/src/pages/leftmenuTestPage.tsx
- client/src/pages/lobbyPage.tsx
- client/src/pages/youtubeTestPage_instructor.tsx
- client/src/pages/youtubeTestPage_participant.tsx
- package.json
- #73 
ClassPage에서 컴포넌트 통합과 리팩토링
1. 소켓 connection status checking component 제작
2. ClassPage에 SocketContext 제공
3. Youtube Component Props 수정
4. 라우팅 설정
5. LeftMenu PropType 추가
1. 소켓 connection status checking component 제작
Classroom Page 내부에서 소켓을 사용해야하기 때문에, 디버깅용 컴포넌트 제작
현재는 socket connection status를 표시해줍니다.
차후에는 소켓 이벤트가 발생할 때마다 메세지를 표시해주는 컴포넌트로 확장시킬 생각입니다.
2. ClassPage에 SocketContext 제공
Classpage안에서 Socket 사용하기 위해 SocketProvider로 context를 제공했습니다.
```js
<Route
...
element={
<SocketProvider url="http://localhost:5000/">
<ClassPage />
</SocketProvider>
}
/>
```
3. Youtube Component Props 수정
**유튜브 컴포넌트를 수정해서, 현철이형 리뷰 요청드립니다**
studentNumber Prop을 memberType으로 변경했습니다.
기존에 studentNumber의 역할이 instructor인지 student인지 구별하는 것에만 쓰이는 것 같아서 memberType enum으로 변경했습니다. 
4. 라우팅 설정
"/class"에서 classPage 렌더링
- …
> Refactor components for integration#73

- client/src/App.tsx
- client/src/pages/classPage.tsx
- client/src/pages/lobbyPage.tsx
- server/src/loader/express.ts
클라이언트 사이드에서 URL 파라미터를 이용해 라우팅하도록 했습니다.
또한 서버사이드에서 리다이렉션 룰을 설정해서 클라이언트에서 유저가 이상한 경로로 서버에 요청했을 경우 /로 리다이렉션되도록 했습니다.
1. 반으로 들어갔을 경우 `class/:classUuid/:memberType`으로 url parameter을 사용하도록 해서, classPage에서 uuid와 memberType을 사용할 수 있도록 했습니다.
멘토님께서 말씀하셨다시피 url에 uuid가 뜨는건 좋지 않은 방법이니 차후에 수정이 필요할 듯 합니다.
```js
<Route
path="class"
path="class/:classUuid/:memberType"
element={
...
```
2. 서버 단에서 이상한 url로 브라우저에서 get이 날아올 경우 `/`로 리다이렉션하도록 했습니다
```js
app.get('/', (req, res) => {
res.sendFile(path.join(__dirname, '../../client/index.html'));
});
app.get('*', (req, res) => {
res.redirect('/');
});
```
> #87/Change Routing Scheme to use url parameters

- server/src/routes/lobbyRoute/index.ts
Join에 사용되는 Query가 문제여서 수정하였습니다.
> #103/Fix query for join class

- client/src/components/chat.tsx
- client/src/components/youtube.tsx
- client/src/pages/chatTestPage.tsx
- client/src/pages/classPage.tsx
- client/src/pages/lecturePage.tsx
- client/src/pages/youtubeTestPage_instructor.tsx
- client/src/pages/youtubeTestPage_participant.tsx
- server/src/ioHandler/chatProtocols.ts
- server/src/ioHandler/index.ts
#74 의 일부 기본적인 기능 구현 - 코드 공유를 위해 PR open한 것! _**merge하지 말기!!**_
Socket `ChatTextMessage` 이벤트를 통해 통신
req, return type은 위키에 정리 - [링크](https://github.com/CS492-FE-Dev-Team-Project/FE-Dev-Client/wiki/API-Specification#2-chattextmessage)
<br>
Socket `OnTimeMarkerClicked` 이벤트 사용 - 위키에 정리 [링크](https://github.com/CS492-FE-Dev-Team-Project/FE-Dev-Client/wiki/API-Specification#6-timemarkerclicked)
<br>
🚨 주의
> Live chatting#74 (Partial, 1차)

- client/src/components/floatConnectionStatus.tsx
- client/src/pages/classPage.tsx
- client/src/pages/lecturePage.tsx
- client/src/types/index.ts
- server/src/data/class.ts
- server/src/data/classManager.ts
- server/src/data/lecture.ts
- server/src/data/marker.ts
- server/src/entity/markerEntity.ts
- server/src/index.ts
- server/src/ioHandler/classProtocols.ts
- server/src/ioHandler/index.ts
- server/src/routes/lobbyRoute/index.ts
- server/src/types/index.ts
#93 및 In-class API (Classroom에서 lecture 리스트 가져오기 get, lecture 생성 create, lecture join 등)를 구현했습니다.
Request 보낼 시 payload로 넘겨줘야 하는값과, Response로 받는 값은 wiki API에 정리해두었습니다 - [링크](https://github.com/CS492-FE-Dev-Team-Project/FE-Dev-Client/wiki/API-Specification#get-lecture-list-)
현재 테스트 코드를 `floatConnectionStatus.tsx` (client/src/components)에 작성해두었으니, 클라이언트 쪽에서 사용하실 때 참고하거나, 아래 코드를 봐주세요
```TSX
// 💡 클라이언트 - Request 보낼 때
// TEST - get lectures
const getLecture = () => {
const payload = JSON.stringify({ classUuid });
socket?.emit('GetLectures', payload);
};
// TEST - create lectures
const createLecture = () => {
const payload = JSON.stringify({
classUuid,
lectureDate: new Date(),
lectureName: 'Thread',
playlist: 'abc'
});
socket?.emit('CreateLecture', payload);
};
// 💡 클라이언트 - Response 받을 떄 …
```
> Lecture entity#93 - In-class API 작업

- client/src/components/timeMarker.tsx
- client/src/components/youtube.tsx
- client/src/pages/classPage.tsx
- client/src/pages/lecturePage.tsx
- client/src/types/index.ts
- package.json
- server/src/data/lecture.ts
- server/src/ioHandler/chatProtocols.ts
- server/src/ioHandler/classProtocols.ts
- server/src/ioHandler/index.ts
- server/src/ioHandler/markerProtocols.ts
- server/src/ioHandler/youtubeProtocols.ts
1. "GetMarkers" 프로토콜
2. 기존에 class를 소켓IO 룸으로 사용하던 API들 Lecture 룸 이용하도록 변경
3. #115 에서 만들어진 웹소켓 프로토콜을 이용해 Client에서 데이터 가져와서 렌더링
1. "GetMarkers" 프로토콜
렉쳐가 주어졌을 때 마커들을 가져오는 프로토콜입니다. 차후 video 인덱스에 따라 다르게 가져오도록 리팩토링 필요.
**Request**
```js
{
classUuid: string,
lectureId: number
}
```
**Response (if succeeded)**
```js
{
markers: Marker[] // marker.ts in server/src/data/marker.ts
status:200
}
```
2. 기존에 class를 소켓IO 룸으로 사용하던 API들 Lecture 룸 이용하도록 변경
- ccb90941a28758a9f9dcb6e52418a29bdf35741c
- 4d8036b04051b466d6cff746e91e508aba067272
3. #115 에서 만들어진 웹소켓 프로토콜을 이용해 Client에서 데이터 가져와서 렌더링
아래의 커밋들 참고하시면 좋을 것 같습니다!
- 22923c963c6a74704f2a44ae41b759afb2990f6f
- b4f0018ce53229cab286dff10af27611063b2ec3
- 1cd8c5b7be625a17eb7c86a005e73128fa7613b3
> Integrate lecture api client#109

- client/src/components/chat.tsx
- client/src/components/youtube.tsx
- client/src/pages/lecturePage.tsx
- server/src/ioHandler/markerProtocols.ts
- 마커 생성 시 같은 lecture의 모든 사람이 볼 수 있게
- 마커 누를 시 discussion 채팅 구현
<br>
→ `markerTextMessageEntity`에 User relation 추가해서 (스키마 변경), 마커 메시지를 누가 작성했는지 표시
> Marker chatting#74

- server/src/entity/markerTextMessageEntity.ts
- server/src/entity/userEntity.ts
- server/src/ioHandler/markerProtocols.ts
마커 메시지 스키마를 변경하여 메세지를 보낸 사람을 기록하도록 했고, 로컬에서 마커 챗에 이름 보이도록 했습니다.
> Extend marker entity#74

- client/src/components/youtube.tsx
- client/src/pages/lecturePage.tsx
- server/src/data/class.ts
- server/src/data/lecture.ts
- server/src/ioHandler/chatProtocols.ts
- server/src/ioHandler/index.ts
- server/src/ioHandler/lectureProtocols.ts
- server/src/ioHandler/markerProtocols.ts
- server/src/ioHandler/youtubeProtocols.ts
- server/src/types/index.ts
#137 에서 mention하신 부분 모두 완료했습니다.
1. SelectVideo Live일 때 broadcasting
2. 비디오 인덱스에 해당하는 마커들만 가져오기
> Add video index logic#74

- client/src/components/audioRecorder.tsx
- client/src/components/chatInput.tsx
- client/src/components/leftmenu/leftmenubutton.tsx
- client/src/components/youtube.tsx
- server/src/ioHandler/chatProtocols.ts
- server/src/ioHandler/classProtocols.ts
- server/src/ioHandler/lectureProtocols.ts
- server/src/ioHandler/markerProtocols.ts
- server/src/ioHandler/youtubeProtocols.ts
1. Leftmenu overflow issue 해결
2. 마커 hover 이펙트 삭제
3. chat input 수정
4. walkie talkie 컴포넌트 수정
> Fix UI issues#142

- client/src/components/lecturecarousel/lecturecard.tsx
- client/src/components/lecturecarousel/lecturecarousel.tsx
렉쳐 카드에서 유튜브 플레이리스트의 썸네일을 가져와서 사용하도록 했습니다.
> Lecture card thumbnail#142

- server/src/ioHandler/lectureProtocols.ts
> #147/Broadcast Live status to class on change

- client/package.json
- client/src/components/lecturecarousel/lecturecarousel.tsx
- client/src/components/leftmenu/leftmenubutton.tsx
- client/src/components/leftmenu/leftmenutab.tsx
- client/src/components/lobbyPage/banner.css
- client/src/components/lobbyPage/banner.tsx
- client/src/pages/lobbyPage.tsx
> #64/basic banner 배너 제작

- client/src/components/leftmenu/leftmenu.tsx
- client/src/pages/classPage.tsx
- client/src/pages/lecturePage.tsx
- client/src/types/index.ts
- server/src/data/lecture.ts
- server/src/ioHandler/index.ts
- server/src/ioHandler/lectureProtocols.ts
- Lecture을 받았을 때 video index설정
- exit lecture protocol 구현
> Fix user enter logic#140

- server/src/ioHandler/index.ts
> Delete Setlang handler

- client/src/components/lecturecarousel/lecturecard.tsx
- client/src/components/lecturecarousel/lecturecarousel.tsx
- client/src/components/leftmenu/leftmenubutton.tsx
- client/src/data/leftmenuData.ts
- client/src/pages/classPage.tsx
- client/src/pages/lecturePage.tsx
- Lecture Card에서 수업 이름 표시
- Left Menu 리뉴얼
- notice, material 삭제
- member type 표시
> Minor fixes#156

- client/src/components/chat.tsx
- client/src/components/classroomPage/AddLecturePage.tsx
- client/src/components/timeMarker.tsx
- client/src/components/youtube.tsx
- client/src/pages/classPage.tsx
- client/src/pages/lecturePage.tsx
- server/src/data/class.ts
- server/src/data/lecture.ts
- server/src/ioHandler/chatProtocols.ts
- server/src/ioHandler/classProtocols.ts
- server/src/ioHandler/lectureProtocols.ts
- server/src/ioHandler/markerProtocols.ts
- server/src/ioHandler/youtubeProtocols.ts
- server/src/routes/translateRoute/index.ts
- server/src/types/index.ts
socket event 호출 시 불필요한 JSON.stringify/parse를 제거하였습니다
> Fix api req type#160
